# This file tells Render exactly how to build and deploy everything.
# It creates your web app AND your free database automatically.
services:
  # This is your Python web application
  - type: web
    name: simple-auth-app
    env: python
    # This is the critical fix: It forces Render to use a stable Python version
    pythonVersion: "3.11"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app"
    envVars:
      # These lines tell the app how to connect to the database below
      - key: DB_HOST
        fromDatabase:
          name: auth-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: auth-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: auth-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: auth-db
          property: password

  # This tells Render to create a free PostgreSQL database for you
  - type: pserv
    name: auth-db
    plan: free # This specifies the free database tier
    postgres:
      version: "14"

